var CACHE='hbk-1791031767';
var PRECACHE=["./", "index.html", "manifest.webmanifest", "icon-180.png", "icon-192.png", "icon-512.png", "clips/again.mp3", "clips/block.mp3", "clips/burn-out-elbows-nonstop.mp3", "clips/burn-out-hooks-nonstop.mp3", "clips/burn-out-kicks-nonstop.mp3", "clips/burn-out-knees-nonstop.mp3", "clips/burn-out-straight-punches-nonstop.mp3", "clips/check-left.mp3", "clips/check-right.mp3", "clips/cross.mp3", "clips/double-jab.mp3", "clips/five.mp3", "clips/four.mp3", "clips/get-ready.mp3", "clips/go.mp3", "clips/inside-low-kick.mp3", "clips/jab.mp3", "clips/lead-elbow.mp3", "clips/lead-hook-to-the-body.mp3", "clips/lead-hook.mp3", "clips/lead-knee.mp3", "clips/lead-teep.mp3", "clips/lead-uppercut.mp3", "clips/left-elbow.mp3", "clips/left-head-kick.mp3", "clips/left-hook-to-the-body.mp3", "clips/left-hook.mp3", "clips/left-inside-low-kick.mp3", "clips/left-kick.mp3", "clips/left-knee.mp3", "clips/left-low-kick.mp3", "clips/left-teep.mp3", "clips/left-up-elbow.mp3", "clips/left-uppercut.mp3", "clips/long-guard.mp3", "clips/low-kick.mp3", "clips/next.mp3", "clips/one-one.mp3", "clips/one.mp3", "clips/overhand-left.mp3", "clips/overhand-right.mp3", "clips/overhand.mp3", "clips/parry.mp3", "clips/pull-back.mp3", "clips/rear-elbow.mp3", "clips/rear-head-kick.mp3", "clips/rear-hook.mp3", "clips/rear-kick.mp3", "clips/rear-knee.mp3", "clips/rear-teep.mp3", "clips/rear-uppercut.mp3", "clips/rest.mp3", "clips/right-elbow.mp3", "clips/right-head-kick.mp3", "clips/right-hook-to-the-body.mp3", "clips/right-hook.mp3", "clips/right-inside-low-kick.mp3", "clips/right-kick.mp3", "clips/right-knee.mp3", "clips/right-low-kick.mp3", "clips/right-teep.mp3", "clips/right-up-elbow.mp3", "clips/right-uppercut.mp3", "clips/roll.mp3", "clips/round-eight.mp3", "clips/round-eighteen.mp3", "clips/round-eleven.mp3", "clips/round-fifteen.mp3", "clips/round-five.mp3", "clips/round-four.mp3", "clips/round-fourteen.mp3", "clips/round-nine.mp3", "clips/round-nineteen.mp3", "clips/round-one-in-ten-seconds.mp3", "clips/round-one.mp3", "clips/round-seven.mp3", "clips/round-seventeen.mp3", "clips/round-six.mp3", "clips/round-sixteen.mp3", "clips/round-ten.mp3", "clips/round-thirteen.mp3", "clips/round-three.mp3", "clips/round-twelve.mp3", "clips/round-twenty.mp3", "clips/round-two.mp3", "clips/session-complete-nice-work.mp3", "clips/six.mp3", "clips/slip.mp3", "clips/step-back.mp3", "clips/switch-head-kick.mp3", "clips/switch-kick.mp3", "clips/switch-knee.mp3", "clips/ten-seconds.mp3", "clips/thirty-seconds.mp3", "clips/three-to-the-body.mp3", "clips/three.mp3", "clips/time.mp3", "clips/twenty-seconds.mp3", "clips/two.mp3", "clips/up-elbow.mp3"];
self.addEventListener('install',function(e){ e.waitUntil(caches.open(CACHE).then(function(c){ return c.addAll(PRECACHE); }).then(function(){ return self.skipWaiting(); })); });
self.addEventListener('activate',function(e){ e.waitUntil(caches.keys().then(function(ks){ return Promise.all(ks.filter(function(k){ return k!==CACHE; }).map(function(k){ return caches.delete(k); })); }).then(function(){ return self.clients.claim(); })); });
function put(req,res){ var c=res.clone(); caches.open(CACHE).then(function(x){ x.put(req,c); }); return res; }
self.addEventListener('fetch',function(e){
  var req=e.request; if(req.method!=='GET') return;
  var url=new URL(req.url);
  if(url.origin===location.origin){
    if(req.mode==='navigate' || url.pathname==='/' || /\/index\.html$/.test(url.pathname)){
      e.respondWith(fetch(req).then(function(r){ return put(req,r); }).catch(function(){ return caches.match(req).then(function(r){ return r||caches.match('index.html'); }); }));
    } else {
      e.respondWith(caches.match(req).then(function(r){ return r||fetch(req).then(function(res){ return put(req,res); }); }));
    }
  } else if(/fonts\.(googleapis|gstatic)\.com$/.test(url.host)){
    e.respondWith(caches.match(req).then(function(r){ var f=fetch(req).then(function(res){ return put(req,res); }).catch(function(){ return r; }); return r||f; }));
  }
});
